### ISSUE TITLE
MITMProxy Support

### ISSUE THREAD

**Issue by arturolc** [vdaburon/har-to-jmeter-convertor#1]
I have been having issues with BrowserMobProxy since that open-source project is no longer maintained. Therefore, I was trying to see if MITMProxy https://github.com/mitmproxy/mitmproxy (a better maintained and more robust solution) would work. 

When converting an HAR file created by MITMProxy I am met with the following exception:

org.xml.sax.SAXException: An invalid XML character (Unicode: 0x3) was found in the node's character data content.
        at java.xml/com.sun.org.apache.xml.internal.serializer.ToStream.accumDefaultEscape(ToStream.java:1749)
        at java.xml/com.sun.org.apache.xml.internal.serializer.ToStream.processDirty(ToStream.java:1644)
        at java.xml/com.sun.org.apache.xml.internal.serializer.ToStream.outputCharacters(ToStream.java:1504)
        at java.xml/com.sun.org.apache.xml.internal.serializer.ToStream$CharacterBuffer$1.flush(ToStream.java:3417)
        at java.xml/com.sun.org.apache.xml.internal.serializer.ToStream$CharacterBuffer.flush(ToStream.java:3506)
        at java.xml/com.sun.org.apache.xml.internal.serializer.ToStream.flushCharactersBuffer(ToStream.java:1559)
        at java.xml/com.sun.org.apache.xml.internal.serializer.ToStream.endElement(ToStream.java:2092)
        at java.xml/com.sun.org.apache.xml.internal.serializer.ToXMLStream.endElement(ToXMLStream.java:542)
        at java.xml/com.sun.org.apache.xml.internal.serializer.ToUnknownStream.endElement(ToUnknownStream.java:318)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:234)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:134)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:96)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:718)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:780)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:394)
        at io.github.vdaburon.jmeter.har.XmlJmx.saveXmFile(XmlJmx.java:1547)
        at io.github.vdaburon.jmeter.har.HarForJMeter.convertHarToJmx(HarForJMeter.java:346)
        at io.github.vdaburon.jmeter.har.HarForJMeter.generateJmxAndRecord(HarForJMeter.java:301)
        at io.github.vdaburon.jmeter.har.HarForJMeter.main(HarForJMeter.java:228)

I scanned the HAR file for 0x3 unicode character, but none were found. I cloned the repo and compiled my own "har-to-jmeter-convertor-6.0-jar-with-dependencies.jar". However, then I realized the JAR is attached in Releases. When I used the one from Releases, the exception did not occur. Not sure why manually compiling it runs into this issue. What mvn command do you use?

**Comment by vdaburon** [comment]
> What mvn command do you use?
I use :
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
and Maven 3.9.6 (IntelliJ Bundled) : 
mvn -DmavenCentralAutoReleaseAfterClose=false clean deploy
or
mvn -DmavenCentralAutoReleaseAfterClose=false clean package
